baseurl = "http://scarred-lands.ctrlz.es"
title = "Scarred Lands"
languageCode = "es-ES"
paginate = 5
Copyright = ""
theme = "casper"
canonifyurls = true

[params]
  description = "Crónica de una aventura de rol"
  cover = "/images/underfaust.jpeg"
  author = "Miguel de la Cruz"
  hideHUGOSupport = true
  share = false