baseurl = "http://mgdelacroix.es/scarred-lands-web/"
title = "Scarred Lands"
languageCode = "es-es"
theme = "heather-hugo"
canonifyurls = true

[params]
  description = "Crónica de una partida de rol"