#!/usr/bin/env bash

IMAGE_NAME=scarred-lands

function build-image {
    docker build --rm -t $IMAGE_NAME docker/
}

function run-server {
    docker run -it \
           --user `id -u` \
           -v `pwd`:/site \
           -e HOME=/site \
           -p 1313:1313 \
           $IMAGE_NAME \
           hugo server -w --bind=0.0.0.0 -D -F
}

function enter-container {
    docker run -it \
           --user `id -u` \
           -v `pwd`:/site \
           -e HOME=/site \
           -p 1313:1313 \
           $IMAGE_NAME \
           bash
}

function generate-site {
    docker run -it \
           --user `id -u` \
           -v `pwd`:/site \
           -e HOME=/site \
           $IMAGE_NAME \
           hugo
}

function usage {
    echo "USAGE: $0 [ build | server | enter | generate ]"
}

case $1 in
    build)
        build-image
        ;;
    server)
        run-server
        ;;
    enter)
        enter-container
        ;;
    generate)
        generate-site
        ;;
    *)
        usage
        ;;
esac
